import type { Metadata } from 'next'
import { Poppins, Urbanist } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap'
})
const urbanist = Urbanist({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-urbanist'
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={(poppins.className, urbanist.variable)}>{children}</body>
    </html>
  )
}
